kind: pipeline
type: docker
name: default

steps:
- name: test
  image: mjehanno/golang_gui:latest
  commands:
  - go test ./...
  - go test ./... -json > test-report.out
  - go test ./... -coverprofile=cover.out
- name: code-analysis
  image: aosapps/drone-sonar-plugin
  settings:
    sonar_host:
      from_secret: sonar_host
    sonar_token:
      from_secret: sonar_token
- name: build
  image: mjehanno/golang_gui:latest
  commands:
    - go build .
- name: package 
  image: mjehanno/golang_gui:latest
  commands:
  - go install github.com/fyne-io/fyne-cross@latest
  - fyne-cross android -pull -app-id $APP_ID -icon $ICON_PATH
  - fyne-cross windows -pull -app-id $APP_ID -icon $ICON_PATH
  - fyne-cross linux -pull -app-id $APP_ID -icon $ICON_PATH
  - fyne-cross windows -pull -app-id $APP_ID -icon $ICON_PATH
  environment:
    APP_ID: com.mjehanno.dnd-spellcounter
    ICON_PATH: ./Icon.png
  when: 
    event:
    - tag
- name: publish
  image: plugins/github-release
  settings:
    api_key: api_token
    files: fyne-cross/bin/*
    title: DRONE_TAG
  when:
    event: 
    - tag

    
