kind: pipeline
type: docker
name: default

steps:
- name: test
  image: mjehanno/golang_gui:latest
  commands:
  - go test ./...
  - go test ./... -cover
- name: code-analysis
  image: aosapps/drone-sonar-plugin
  settings:
    sonar_host:
      from_secret: sonar_host
    sonar_token:
      from_secret: sonar_token
- name: build
  image: mjehanno/golang_gui:latest
  commands:
    - go build .
- name: package 
  image: mjehanno/golang_gui:latest
  commands:
  - go install github.com/fyne-io/fyne-cross@latest
  - fyne-cross android -pull -app-id $APP_ID -icon $ICON_PATH
  - fyne-cross windows -pull -app-id $APP_ID -icon $ICON_PATH
  - fyne-cross linux -pull -app-id $APP_ID -icon $ICON_PATH
  - fyne-cross windows -pull -app-id $APP_ID -icon $ICON_PATH
  environment:
    APP_ID: com.mjehanno.dnd-spellcounter
    ICON_PATH: ./Icon.png
  when: 
    event:
    - tag
    
